name: Build OpenSearch from source, run tests and release.

env:
  VERSION: 2.6.0
  RELEASE: edge

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    name: Build and Run Tests
    uses: ./.github/workflows/ci.yaml

  publish:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - ci-tests
    steps:
      - name: Install required dependencies
        run: |
          sudo apt-get update

          # docker
          sudo snap install docker
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker

          # skopeo
          sudo snap install --devmode --channel edge skopeo

      - name: Download rock file
        uses: actions/download-artifact@v3
        with:
          name: opensearch_rock_amd64
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish rock to Store
        run: |
          sudo skopeo \
              --insecure-policy \
              copy \
              oci-archive:opensearch_${{env.VERSION}}_amd64.rock \
              docker-daemon:opensearch:${{env.VERSION}}
          
          docker push "charmed/opensearch:${{env.VERSION}}"
