name: Publish to GHCR

env:
  RELEASE: edge

on:
  push:
    branches:
      - 2-24.04/edge

jobs:
  ci-tests:
    name: Build and Run Tests
    uses: ./.github/workflows/ci.yaml

  publish:
    name: publish
    runs-on: [self-hosted, linux, X64, jammy, large]
    timeout-minutes: 15
    needs:
      - ci-tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install required dependencies
        run: |
          # docker
          # FIXME: v27.2.0 reports "...client version 1.22 is too old..." when trying to copy the
          # rock to the local repository --revision=2932
          sudo snap install docker --channel=latest/stable --revision=2932
          sudo addgroup --system docker; sudo adduser $USER docker
          newgrp docker
          sudo snap disable docker; sudo snap enable docker

          # skopeo
          sudo snap install --devmode --channel edge skopeo
          
          # yq
          sudo snap install yq

      - name: Download rock file
        uses: actions/download-artifact@v4
        with:
          name: opensearch_rock_amd64
          path: .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Publish rock to Store
        run: |
          version="$(cat rockcraft.yaml | yq .version)"
          
          base="$(cat rockcraft.yaml | yq .base)"
          base="${base#*@}"
          
          # push major version to edge
          major_tag_version="${version%%.*}-${{ env.RELEASE }}"
          sudo skopeo \
              --insecure-policy \
              copy \
              oci-archive:opensearch_${version}_amd64.rock \
              docker-daemon:ghcr.io/canonical/opensearch:${major_tag_version}
          docker push ghcr.io/canonical/opensearch:${major_tag_version}
          
          ### push full version to edge
          tag_version="${version}-${base}_${{ env.RELEASE }}"
          echo "Publishing opensearch:${tag_version}"
          sudo skopeo \
              --insecure-policy \
              copy \
              oci-archive:opensearch_${version}_amd64.rock \
              docker-daemon:ghcr.io/canonical/opensearch:${tag_version}
          docker push ghcr.io/canonical/opensearch:${tag_version}
