name: Trivy Security Scanner
on:
  push:
    branches:
      - main
  schedule:
    - cron: '53 0 * * *' # Daily at 00:53 UTC
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  scan:
    name: Trivy scan
    needs: 
      - build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
          sudo snap install yq

      - uses: actions/download-artifact@v3
        with:
          name: charmed-opensearch

      - name: Import locally
        run: |
          sudo skopeo --insecure-policy copy \
            oci-archive:${{ needs.build.outputs.rock }} \
            docker-daemon:trivy/charmed-opensearch:test

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'trivy/charmed-opensearch:test'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'